name: ci-cd-prod
run-name: "Production Deploy - ${{ github.event.inputs.branch }} → ${{ github.event.inputs.image_tag }}"

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Branch to checkout for charts'
        required: true
        default: main
      image_tag:
        type: string
        description: 'Image tag/sha produced by the dev workflow'
        required: true

permissions:
  contents: read

env:
  REGISTRY_HOST: forgejo.gitgud.zip
  REGISTRY_NAMESPACE: stasaberg

jobs:
  validate-tag:
    name: Validate Image Tag
    runs-on: self-hosted
    steps:
      - name: Validate image tag format
        run: |
          TAG="${{ github.event.inputs.image_tag }}"
          echo "Validating tag: ${TAG}"

          # Prevent deploying dangerous tags
          if [[ "$TAG" == "latest" ]] || [[ "$TAG" == "dev" ]]; then
            echo "❌ ERROR: Cannot deploy 'latest' or 'dev' tags to production"
            exit 1
          fi

          # Warn if not a commit SHA
          if ! [[ "$TAG" =~ ^[a-f0-9]{40}$ ]]; then
            echo "⚠️  WARNING: Tag doesn't look like a commit SHA (expected 40 hex chars)"
            echo "    This is allowed but not recommended for production"
          fi

          echo "✓ Tag validation passed"

  deploy-prod:
    runs-on: self-hosted
    needs: validate-tag
    steps:
      - name: Checkout charts
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Helm
        uses: azure/setup-helm@bf6a7d304bc2fdb57e0331155b7ebf2c504acf0a  # v4

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/kubeconfig
          chmod 600 $HOME/kubeconfig
          echo "KUBECONFIG=$HOME/kubeconfig" >> $GITHUB_ENV

      - name: Helm upgrade (production)
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          helm upgrade --install my-stupid-website charts/my-stupid-website \
            --namespace my-stupid-website --create-namespace \
            --set-string image.tag="$IMAGE_TAG" \
            --rollback-on-failure --wait --kube-insecure-skip-tls-verify

      - name: Notify deployment success
        if: success() && secrets.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -fsSL -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"content":"✅ **Production deployment successful**\n**Service:** my-stupid-website\n**Tag:** `${{ github.event.inputs.image_tag }}`\n**Deployer:** ${{ github.actor }}"}'
