name: terminal-service-prod

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Branch to checkout for charts'
        required: true
        default: main
      image_tag:
        type: string
        description: 'Image tag/sha from the dev workflow'
        required: true

permissions:
  contents: read

env:
  REGISTRY_HOST: forgejo.gitgud.zip
  REGISTRY_NAMESPACE: stasaberg

jobs:
  deploy-prod:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/kubeconfig
          chmod 600 $HOME/kubeconfig
          echo "KUBECONFIG=$HOME/kubeconfig" >> $GITHUB_ENV
      - name: Helm upgrade (prod - terminal)
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          helm upgrade --install my-stupid-website-terminal charts/terminal-service \
            --namespace my-stupid-website --create-namespace \
            --set-string image.tag="$IMAGE_TAG" \
            --rollback-on-failure --wait --kube-insecure-skip-tls-verify
