autoscaling:
  enabled: false

replicaCount: 1

env:
  SANDBOX_ROOT: /sandbox
  COMMAND_TIMEOUT_MS: "4000"
  MAX_PAYLOAD_BYTES: "2048"
  MAX_OUTPUT_BYTES: "16384"
  CORS_ALLOW_ORIGIN: "https://dev.gitgud.qzz.io"

serviceAuth:
  existingSecret: radio-service-env-dev
  secretKey: STATIONS_REFRESH_TOKEN
