radioService:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/stasaberg/radio-service
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 4010
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 101
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  service:
    type: ClusterIP
    port: 4010
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 10
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
  env:
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: REDIS_URL
          optional: true
    - name: STATIONS_CACHE_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: STATIONS_CACHE_KEY
          optional: true
    - name: STATIONS_CACHE_TTL
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: STATIONS_CACHE_TTL
          optional: true
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: MINIO_ENDPOINT
          optional: true
    - name: MINIO_REGION
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: MINIO_REGION
          optional: true
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: MINIO_SECRET_KEY
    - name: MINIO_BUCKET
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: MINIO_BUCKET
          optional: true
    - name: STATIONS_OBJECT_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: STATIONS_OBJECT_KEY
          optional: true
    - name: RADIO_BROWSER_BASE_URL
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: RADIO_BROWSER_BASE_URL
          optional: true
    - name: RADIO_BROWSER_STATIONS_PATH
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: RADIO_BROWSER_STATIONS_PATH
          optional: true
    - name: RADIO_BROWSER_LIMIT
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: RADIO_BROWSER_LIMIT
          optional: true
    - name: STATIONS_REFRESH_TOKEN
      valueFrom:
        secretKeyRef:
          name: radio-service-env
          key: STATIONS_REFRESH_TOKEN
          optional: true
    - name: ALLOW_INSECURE_TRANSPORT
      value: "true"
