radioService:
  enabled: true
  replicaCount: 1
  env:
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: REDIS_URL
          optional: true
    - name: STATIONS_CACHE_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: STATIONS_CACHE_KEY
          optional: true
    - name: STATIONS_CACHE_TTL
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: STATIONS_CACHE_TTL
          optional: true
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: MINIO_ENDPOINT
          optional: true
    - name: MINIO_REGION
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: MINIO_REGION
          optional: true
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: MINIO_SECRET_KEY
    - name: MINIO_BUCKET
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: MINIO_BUCKET
          optional: true
    - name: STATIONS_OBJECT_KEY
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: STATIONS_OBJECT_KEY
          optional: true
    - name: STATIONS_REFRESH_TOKEN
      valueFrom:
        secretKeyRef:
          name: radio-service-env-dev
          key: STATIONS_REFRESH_TOKEN
          optional: true
    - name: ALLOW_INSECURE_TRANSPORT
      value: "true"
